[environments.default]
url="jdbc:postgresql://localhost:5434/practica_13_04_2026"
user="postgres"
password="admin123"
schemas=["public"]

[flyway]
locations=["filesystem:sql", "filesystem:repeatable"]